# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='ClimateInner',
            fields=[
                ('climateId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('temp_inner', models.FloatField()),
            ],
            options={
                'db_table': 'climate_inner',
            },
        ),
        migrations.CreateModel(
            name='ClimateNet',
            fields=[
                ('climateNetId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('temp_net', models.FloatField()),
                ('cityId', models.ForeignKey(db_column='cityId', on_delete=django.db.models.deletion.CASCADE, to='climateApp.City')),
            ],
            options={
                'db_table': 'climate_net',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(blank=True, max_length=45, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('terminalId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deviceEui', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('deviceAddr', models.ForeignKey(db_column='deviceAddr', on_delete=django.db.models.deletion.CASCADE, to='climateApp.City', to_field='cityName')),
                ('username', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'terminal',
            },
        ),
        migrations.AddField(
            model_name='climateinner',
            name='terminalId',
            field=models.ForeignKey(db_column='terminalId', on_delete=django.db.models.deletion.CASCADE, to='climateApp.Terminal'),
        ),
        migrations.AlterUniqueTogether(
            name='climatenet',
            unique_together=set([('date', 'time', 'cityId')]),
        ),
        migrations.AlterUniqueTogether(
            name='climateinner',
            unique_together=set([('date', 'time', 'terminalId')]),
        ),
    ]
