# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climateApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal',
            old_name='username',
            new_name='user',
        ),
    ]
