# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climateApp', '0002_auto_20170801_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal',
            old_name='user',
            new_name='username',
        ),
    ]
